//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Inventory_Management_system.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblAdmin
    {
        public int AdminId { get; set; }
        public string AdminName { get; set; }
        public string AdminMobile { get; set; }
        public string AdminEmail { get; set; }
        public System.DateTime AdminDOB { get; set; }
        public bool AdminGender { get; set; }
        public int QualificationId { get; set; }
        public int RoleId { get; set; }
        public string AdminPassword { get; set; }
        public Nullable<bool> AdminDeleted { get; set; }
    
        public virtual tblQualification tblQualification { get; set; }
        public virtual tblRole tblRole { get; set; }
    }
}
