//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Inventory_Management_system.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblManager
    {
        public int ManId { get; set; }
        public string ManName { get; set; }
        public string ManMobile { get; set; }
        public string ManEmail { get; set; }
        public System.DateTime ManDOB { get; set; }
        public string ManGender { get; set; }
        public Nullable<int> ManSalary { get; set; }
        public int QualificationId { get; set; }
        public int RoleId { get; set; }
        public Nullable<System.DateTime> ManJoiningDate { get; set; }
        public string ManPassword { get; set; }
        public Nullable<bool> ManDeleted { get; set; }
    
        public virtual tblQualification tblQualification { get; set; }
        public virtual tblRole tblRole { get; set; }
    }
}
