//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Inventory_Management_system.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblStaff
    {
        public int StaffId { get; set; }
        public string StaffName { get; set; }
        public string StaffMobile { get; set; }
        public string StaffEmail { get; set; }
        public System.DateTime StaffDOB { get; set; }
        public bool StaffGender { get; set; }
        public Nullable<int> StaffSalary { get; set; }
        public int QualificationId { get; set; }
        public int RoleId { get; set; }
        public Nullable<System.DateTime> StaffJoiningDate { get; set; }
        public string StaffPassword { get; set; }
        public Nullable<bool> StaffDeleted { get; set; }
    
        public virtual tblQualification tblQualification { get; set; }
        public virtual tblRole tblRole { get; set; }
    }
}
